const structuredFields = [
  'sku',
  'manufacturer',
  'productNumber',
  'productText',
  'productVersion',
  'eanOrUpc',
  'countryOfOrigin',
  'itemCategory',
  'packaging',
  'condition',
  'externalCondition',
  'workingCondition',
  'quantity',
  'batchSize',
  'storagePosition',
  'externalNote',
  'internalNote',
  'priceEur',
  'status',
  'advancedInformation',
  'weightKg',
  'heightMm',
  'widthMm',
  'lengthMm',
  'hsCode',
  'itemGroup',
  'reference',
  'sendingType',
  'sellingType',
  'link',
];

export function buildExtractionPrompt() {
  return [
    'Extract product label data to a strict JSON object.',
    'Return only valid JSON. Do not add markdown, code fences, comments, or prose.',
    'Use top-level keys: structured_json and auxiliary_text_optional.',
    'structured_json must be an object with exactly these keys:',
    structuredFields.join(', '),
    'If a value is unknown, use null.',
    'Use number for numeric fields and string for text fields.',
    'Preserve literal barcode-like strings in text fields like eanOrUpc without formatting changes.',
  ].join(' ');
}
